services:
  postgres:
    image: postgres:17.5
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lego
      POSTGRES_PASSWORD: lego
      POSTGRES_DB: lego
    healthcheck:
      test: "/usr/bin/pg_isready"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  lego-data:
    image: postgres:17.5
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./resources/data/:/data
    environment:
      PGUSER: lego
      PGPASSWORD: lego
      PGDATABASE: lego
      PGHOST: postgres
    entrypoint: >
      /bin/sh -c '
        psql -f /data/lego.sql
      '

volumes:
  database:
